#!/usr/bin/env bash
# generate_inventory.sh
# ─────────────────────────────────────────────────────────────────────────────
# Reads Terraform output and writes a fresh Ansible inventory file.
# Run this AFTER terraform apply succeeds.
#
# Usage:
#   chmod +x scripts/generate_inventory.sh
#   ./scripts/generate_inventory.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../terraform"
INVENTORY_FILE="${SCRIPT_DIR}/../ansible/inventory.ini"
SSH_KEY="${HOME}/.ssh/id_rsa"
SSH_USER="ubuntu"

echo ">>> Reading Terraform outputs from: ${TF_DIR}"

# Fetch the JSON output; jq extracts the list of IPs
PUBLIC_IPS=$(terraform -chdir="${TF_DIR}" output -json instance_public_ips | jq -r '.[]')

if [[ -z "${PUBLIC_IPS}" ]]; then
  echo "ERROR: No public IPs found. Did terraform apply succeed?"
  exit 1
fi

echo ">>> Writing inventory to: ${INVENTORY_FILE}"

# Overwrite inventory file
cat > "${INVENTORY_FILE}" <<-EOF
# Auto-generated by generate_inventory.sh — do not edit manually
# Regenerate with: ./scripts/generate_inventory.sh

[web_servers]
EOF

while IFS= read -r ip; do
  echo "${ip} ansible_user=${SSH_USER} ansible_ssh_private_key_file=${SSH_KEY}" >> "${INVENTORY_FILE}"
  echo "    Added: ${ip}"
done <<< "${PUBLIC_IPS}"

cat >> "${INVENTORY_FILE}" <<-EOF

[web_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF

echo ""
echo "✅  Inventory written:"
cat "${INVENTORY_FILE}"

echo ""
echo ">>> Next step:"
echo "    cd ansible && ansible-playbook -i inventory.ini playbook.yml"
